server.document-root = "/opt/www/kzlp"
server.port          = 8088
server.bind          = "0.0.0.0"
server.pid-file      = "/opt/var/run/lighttpd.pid"
server.username      = ""
server.groupname     = ""

server.modules = (
  "mod_cgi",
  "mod_setenv"
)

index-file.names = ( "index.html" )

cgi.assign = (
  ".cgi" => "/opt/bin/sh"
)

setenv.add-response-header = (
  "Cache-Control" => "no-cache, no-store, must-revalidate",
  "Pragma"        => "no-cache"
)
